config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :categories
  resources :tasks do
    member do
      put :toggle_completion
    end
  end

  get '/tailwindcss/base', to: redirect('/path/to/your/base.css')
  get '/tailwindcss/components', to: redirect('/path/to/your/components.css')
  get '/tailwindcss/utilities', to: redirect('/path/to/your/utilities.css')

 unauthenticated do
    root to: "pages#landing", as: :unauthenticated_root
  end

  # Dashboard for signed-in users:
  authenticated :user do
    root to: "pages#home", as: :authenticated_root
  end


  root to:"pages#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
    validates :name, :details, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    belongs_to :user
    validates :title, :category, :details, :date_due, presence:true

    after_initialize :set_default_status, unless: :persisted?

    private
  
    def set_default_status
      self.completed = false
    end
  end    

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :categories
  validates :first_name, :last_name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    

    protected

    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name terms_and_conditions])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
    end

    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :set_category, only: [:show, :edit, :update, :destroy]
  
    # GET /categories
    def index
        @categories = current_user.categories
    end
  
    # GET /categories/1
    def show
    end
  
    # GET /categories/new
    def new
      @category = Category.new
    end
  
    # GET /categories/1/edit
    def edit
    end
  
    # POST /categories
    def create
      @category = current_user.categories.build(category_params)
  
      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        
        render :new
      end
    end
  
    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :details)
    end
 
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include TasksHelper

  skip_before_action :authenticate_user!, only: [:landing]

  # GET  /       ← public splash
  def landing
    # nothing needed here—just renders views/pages/landing.html.erb
  end


  def home
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @tasks = @category.tasks.where(user_id: current_user.id).order(completed: :asc, date_due: :asc)
    else
      @tasks = Task.where(user_id: current_user.id).order(completed: :asc, date_due: :asc)
    end
  
    @categories = Category.where(user_id: current_user.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include TasksHelper
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    # GET /tasks
    def index

      
      if params[:category_id]
        @category = Category.find(params[:category_id])
        @tasks = @category.tasks.where(user_id: current_user.id)
      else
    
        @tasks = Task.where(user_id: current_user.id).order(completed: :asc, date_due: :asc)
        
      end

      today = Time.zone.today
      
    end
    
    

    # GET /tasks/1
    def show
    end
  
    # GET /tasks/new
    def new
        if Category.count.zero?
            flash[:alert] = 'Please add a category first before creating a task'
            redirect_to new_category_path
            else
            @task = Task.new
        end
    end
  
    # GET /tasks/1/edit
    def edit
    end
  
    # POST /tasks
    def create
    @task = current_user.tasks.build(task_params)
    @task.user = current_user # Assign the task to the current logged-in user
    @task.completed = false
  
        if @task.save
            redirect_to @task, notice: 'Task was successfully created.'
            
         else
          flash.now[:alert] = "Task could not be created due to the following errors: #{task_errors(@task)}"
            render :new
        end
    
    end
  
    # PATCH/PUT /tasks/1
    def update
      if @task.update(task_params)
        redirect_to @task, notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /tasks/1
    def destroy
      @task.destroy
      redirect_to tasks_url, notice: 'Task was successfully destroyed.'
    end
  
     #completed task
    def toggle_completion
    @task = Task.find(params[:id])
    @task.update(completed: !@task.completed)

    redirect_to tasks_url
    end



    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end
    
     # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :details, :date_due, :category_id)
    end
  

  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def label_class
        "block text-sm font-medium leading-6 text-gray-900"
    end

    def input_class
        "block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
    end

    def form_button_class
        "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
    end

    def checkbox_class
        "h-5 w-5 rounded-md border-gray-200 bg-white shadow-sm"
    end

    end

app/helpers/tasks_helper.rb
# app/helpers/tasks_helper.rb
module TasksHelper
  
  def tasks_due_today(user)
    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    user.tasks.where(date_due: today).order(completed: :asc, date_due: :asc)
  end

  def tasks_not_due_today(user)
    today = Date.current
    user.tasks.where.not(date_due: today.all_day).order(completed: :asc, date_due: :asc)
  end

  def task_errors(task)
    task.errors.full_messages.join(', ')
  end


end

app/views/categories/_form.html.erb
<!-- app/views/tasks/_form.html.erb -->
<%= form_with(model: @category, local: true) do |form| %>
  <div class="field mb-6">
    <%= form.label :name, class: label_class %>
    <%= form.text_field :name, class: input_class %>
  </div>

  <div class="field mb-6">
    <%= form.label :details, class: label_class %>
    <%= form.text_area :details, class: input_class %>
  </div>

  

  <div class="actions mb-6 ">
    <%= form.submit class: form_button_class %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for(:page_title, "Edit Category") %>

<div class="flex justify-center">
  <div class="w-1/3"> 

<%= render 'form' %>


<div class="flex justify-between">
	<div>
		<button class="inline-flex items-center px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
			</svg>

			<%= link_to 'Back', categories_path %>
		</button>
	</div>
    <div>

        <%= button_to @category, method: :delete, data: { action: "click->confirm#confirm" }, class: 'inline-flex items-center px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
        </svg>
        Delete
        <% end %>
    </div>
</div>

</div>
</div>

app/views/categories/index.html.erb
<% content_for(:page_title, "Your Categories") %>

  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <button class="inline-flex items-center mx-auto max-w-7x mt-4 px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
    </svg>

    <%= link_to 'New Category', new_category_path %>
  </button>
  <div class= "pt-2" >
    <!-- list break -->
    
    <% @categories.sort_by(&:updated_at).each do |category| %>
      
      <div class="p-4 bg-white border rounded-xl text-gray-800 space-y-2">
      
        <div class="flex justify-between">
          <%= link_to category, class: "font-bold hover:text-yellow-800 hover:underline" do %>
            <%= category.name %>
          <% end %>
          <div class="text-gray-400 text-xs"> <%= link_to tasks_path(category_id: category.id), class: "hover:underline"  do %>
          <p class="text-sm leading-6 text-gray-900">
           <%= category.tasks.where(user_id: current_user.id).count %> tasks
          </p>
          <% end %>
          </div>
        
          
          </div>
        <div class="flex justify-between">
        <div class="text-sm text-gray-600">
          <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="text-gray-800 inline align-middle mr-1" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
          </svg><%= truncate(category.details, length: 100) %>
        </div>
        <div><strong>Last Updated:</strong> <%= category.updated_at.strftime('%Y-%m-%d %H:%M') %></div>
     
        </div>
      </div>
      
    <%end%>
    <!-- list break -->
  </div>






</div>

app/views/categories/new.html.erb
<% content_for(:page_title, "New Category") %>

<div class="flex justify-center">
  <div class="w-1/3"> 
<%= render 'form' %>

<button class="inline-flex items-center px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
			</svg>

			<%= link_to 'Back', categories_path %>
		</button>

</div>
</div>

app/views/categories/show.html.erb
<% content_for(:page_title, "Your Category") %>

<div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest"><%= link_to tasks_path(category_id: @category.id), class: "hover:underline"  do %><%= @category.tasks.where(user_id: current_user.id).count %> tasks<%end%></h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1"><%= @category.name %></h1>
        <div class="flex mb-4">
          <span class="flex items-center">
            
           
          </span>
          <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200">
            
          </span>
        </div>
		<p class="leading-relaxed"><%= @category.details %></p>

		
		<div class="flex mt-5">

		<button class="inline-flex items-center px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
						<path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
			</svg>

			<%= link_to 'Edit', edit_category_path(@category) %> 
		</button>


		<button class="inline-flex items-center ml-5 px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
			</svg>

			<%= link_to 'Back', categories_path %>
		</button>
		</div>

app/views/pages/home.html.erb
<% content_for(:page_title, "Welcome to ChronoMemo #{current_user.first_name.capitalize}") %>

<div class="grid grid-cols-3 gap-x-20">
  <div>
    <h2 class="text-2xl font-bold mb-4">Stats</h2>
    <div class="grid grid-cols-2 gap-4">
      <div class="col-span-2">
        <div class="p-4 bg-green-100 rounded-xl">
          <div class="font-bold text-xl text-gray-800 leading-none"><%= current_user.first_name %>!</div>
          <div class="mt-5">
            <button type="button" class="inline-flex items-center justify-center py-2 px-3 rounded-xl bg-white text-gray-800 hover:text-green-500 text-sm font-semibold transition">
             <a href="/tasks"> View All Tasks </a>
            </button>
          </div>
        </div>
      </div>
      <div class="col-span-1">
      <div class="p-4 bg-yellow-100 rounded-xl text-gray-800">
        <div class="font-bold text-2xl leading-none">
        <%= Task.where(user_id: current_user.id, completed:true).count %> tasks
        </div>
        <div class="mt-2"> Finished</div>
      </div>
      </div>
      <div class="col-span-1">
      <div class="p-4 bg-yellow-100 rounded-xl text-gray-800">
        <div class="font-bold text-2xl leading-none">
        <%= Category.where(user_id: current_user.id).count %> Categories
        </div>
      </div>  
      </div>
      <div class="col-span-2">
        <div class="p-4 bg-purple-100 rounded-xl text-gray-800">
          <div class="font-bold text-xl leading-none">Tasks due today</div>
          <div class="mt-2">
          <%= Task.where(user_id: current_user.id, completed: true).where('date_due::date <= ?', Date.today).count %> 
            of
          <%= Task.where(user_id: current_user.id).where('date_due::date <= ?', Date.today).count %>  completed</div>
        </div>
      </div>
    </div>
  </div>
  
  <div>
    <h2>Other Tasks</h2>
    <div style="height: 400px; overflow-y: auto;">
      <!-- list break -->
      <% @tasks.each do |task| %>
      
      <div class="p-4 bg-white border rounded-xl text-gray-800 space-y-2">
      
        <div class="flex justify-between">
          <%= link_to task.category do %>
          <div class="text-gray-400 text-xs"><%= task.category.name %></div>
          <%end%>
          <div class="text-gray-400 text-xs">
            <% if task.completed %>
            <span class="text-green-600 font-bold">(Completed)</span>
            <% elsif task.date_due < Time.zone.now.beginning_of_day %>
            <span class="text-red-600 font-bold">(Overdue)</span>
            <% elsif !task.completed && task.date_due >= Time.zone.now.beginning_of_day && task.date_due <= Time.zone.now.end_of_day %>
            <span class="text-red-600 font-bold">(Due Today)</span>
            
           
            
            <% end %>
          </div>
         </div>
         <%= link_to task, class: "font-bold hover:text-yellow-800 hover:underline" do %>
      <%= task.title %>
    <% end %>
        <div class="text-sm text-gray-600">
          <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="text-gray-800 inline align-middle mr-1" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
          </svg><%= truncate(task.details, length: 100) %>
        </div>
     
        
      </div>
      
      <%end%>
      <!-- list break -->
    </div>
  </div>

  <div>
    <h2>Categories</h2>
    <div>
      <!-- list break -->
      <% @categories.each do |category| %>
      
      <div class="p-4 bg-white border rounded-xl text-gray-800 space-y-2">
      
        <div class="flex justify-between">
                   <div class="text-gray-400 text-xs"> <%= link_to tasks_path(category_id: category.id) do %>
                    <p class="text-sm leading-6 text-gray-900">
                      <%= category.tasks.where(user_id: current_user.id).count %> tasks
                    </p>
                    <% end %>
                  </div>
        </div>
          <%= link_to category, class: "font-bold hover:text-yellow-800 hover:underline" do %>
          <%= category.name %>
          <% end %>
        <div class="text-sm text-gray-600">
          <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="text-gray-800 inline align-middle mr-1" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
          </svg><%= truncate(category.details, length: 100) %>
        </div>
     
        
      </div>
      
      <%end%>
      <!-- list break -->
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb

<% content_for(:page_title, "Edit Task") %>

<div class="flex justify-center">
  <div class="w-1/3"> 

<%= render 'form' %>


<div class="flex justify-between">
	<div>
		<button class="inline-flex items-center px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
			</svg>

			<%= link_to 'Back', tasks_path %>
		</button>
	</div>
    <div>

        <%= button_to @task, method: :delete, data: { action: "click->confirm#confirm" }, class: 'inline-flex items-center px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
        </svg>
        Delete
        <% end %>
    </div>
</div>

</div>
</div>

app/views/tasks/index.html.erb
<% content_for(:page_title, "Your Tasks") %>
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    
    <button class="inline-flex items-center mx-auto max-w-7x mt-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md">
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
              </svg>

	<%= link_to 'New Task', new_task_path %> 
  </button>
    <div class= "pt-2" style="height: 600px; overflow-y: auto;">
      <!-- list break -->
      <% @tasks.each do |task| %>
      
      <div class="p-4 bg-white border rounded-xl text-gray-800 space-y-2">
        <!-- the rest of your code to display a task -->
        <div class="flex justify-between">
          <%= link_to task.category do %>
          <div class="text-gray-400 text-xs"><%= task.category.name %></div>
          <%end%>
          <div class="text-gray-400 text-xs">
            <% if !task.completed && task.date_due < Time.zone.now.beginning_of_day %>
            <span class="text-red-600 font-bold">(Overdue)</span>
            <% elsif !task.completed && task.date_due >= Time.zone.now.beginning_of_day && task.date_due <= Time.zone.now.end_of_day %>
            <span class="text-red-600 font-bold">(Due Today)</span>
            <% else %>
       
            <% end %>
          </div>
         </div>
         <%= link_to task, class: "font-bold hover:text-yellow-800 hover:underline" do %>
         <% if task.completed %>
          <del><%= task.title %></del>
          <% else %>
          <%= task.title %>
          <% end %>
    <% end %>
    <div class="flex justify-between">
        <div class="text-sm text-gray-600">
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="text-gray-800 inline align-middle mr-1" viewBox="0 0 16 16">
              <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
            </svg><%= truncate(task.details, length: 250) %>
        </div>
        <div><strong>Due:</strong> <%= task.date_due.strftime('%Y-%m-%d') %>
        
       <%= button_to 'Completed', toggle_completion_task_path(task), method: :put, class: "text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 #{'bg-gray-500 hover:bg-gray-600 focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80' unless task.completed} #{'bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 shadow-lg shadow-green-500/50 dark:shadow-lg dark:shadow-green-800/80' if task.completed}" %>
    </div>
     
        </div>
         
      </div>
      
      <%end%>
   
    </div>

    

  </div>

app/views/tasks/new.html.erb
<% content_for(:page_title, "New Task") %>

<div class="flex justify-center">
  <div class="w-1/3"> 
<%= render 'form' %>

<button class="inline-flex items-center px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
			</svg>

			<%= link_to 'Back', tasks_path %>
		</button>

</div>
</div>

app/views/tasks/show.html.erb
<% content_for(:page_title, "Your Task") %>

<div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest"><%= @task.category.name %></h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1"><%= @task.title %></h1>
        <div class="flex mb-4">
          <span class="flex items-center">
            
            <span class="text-gray-600 ml-3">Due: <%= @task.date_due %></span>
          </span>
          <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200">
            
          </span>
        </div>
		<p class="leading-relaxed">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam indxgo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean shorts keytar banjo tattooed umami cardigan.</p>

		
		<div class="flex mt-5">

		<button class="inline-flex items-center px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
						<path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
			</svg>

			<%= link_to 'Edit', edit_task_path(@task) %> 
		</button>


		<button class="inline-flex items-center ml-5 px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-md">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
			</svg>

			<%= link_to 'Back', tasks_path %>
		</button>
		</div>